apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: another-pipeline-id
      description: the pipeline Id of another tekton pipeline to trigger
    - name: manual-trigger
      description: manual trigger name of another tekton pipeline
    - name: apikey
      description: the ibmcloud api key
    - name: api
      description: the ibmcloud api endpoint
      default: "https://cloud.ibm.com"
    - name: region
      description: the ibmcloud login region
      default: "us-south"
  resourcetemplates:
  # CD context defined as a configmap because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        API: $(params.api)
        REGION: $(params.region)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: another-pipeline-id
          value: $(params.another-pipeline-id)
        - name: manual-trigger
          value: $(params.manual-trigger)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: another-pipeline-id
      description: the pipeline Id of another tekton pipeline to trigger
      value: $(event.another-pipeline-id)
    - name: manual-trigger
      description: manual trigger name of another tekton pipeline
      value: $(event.manual-trigger)
    - name: apikey
      description: the ibmcloud api key
      value: $(event.apikey)
    - name: repository
      value: $(event.repository)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template