apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: another-pipeline-id
      description: the pipeline Id of another tekton pipeline to trigger
    - name: manual-trigger
      description: manual trigger name of another tekton pipeline
    - name: apikey
      description: the ibmcloud api key
    - name: api
      description: the ibmcloud api endpoint
      default: "https://cloud.ibm.com"
    - name: region
      description: the ibmcloud login region
      default: "us-south"
    - name: repository
      default: "https://github.com/SidneyJiang/SimleTestWithMocha.git"
    - name: toolchain-id
      description: the toolchain id
  resourcetemplates:
  # CD context defined as a configmap because it is immutable information
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: cd-config
      data:
        API: $(params.api)
        REGION: $(params.region)
        UID: $(uid)
        MYTOOLCHAIN: |
          {"toolchain_guid":"bf5fa00f-ddef-4298-b87b-aa8b6da0e1a6","name":"very simple one","description":"empty-toolchain-20191127221414804","key":"empty-toolchain-20191127221414804_19c29990ffe42ce260f5a5cb64f54169_us-south","container":{"guid":"19c29990ffe42ce260f5a5cb64f54169","type":"resource_group_id"},"crn":"crn:v1:staging:public:toolchain:us-south:a/0ba224679d6c697f9baee5e14ade83ac:bf5fa00f-ddef-4298-b87b-aa8b6da0e1a6::","created":"2019-11-27T22:14:44.662Z","updated_at":"2020-01-29T15:12:26.662Z","creator":"IBMid-310001SN19","generator":"otc_setup","template":{"getting_started":"**Your toolchain is ready!**\n**Quick start:** You can now add tool integrations. For step-by-step instructions, see the [tutorial](https://www.ibm.com/cloud/garage/tutorials/create-a-custom-toolchain?task=2) for this toolchain.","services_total":0,"name":"Build your own toolchain","type":"template","url":"https://github.com/open-toolchain/empty-toolchain","source":"repo","locale":"en"},"tags":[],"lifecycle_messaging_webhook_id":"4d3d8973016c55f1fb35c6ae2d7a4808","region_id":"ibm:ys1:us-south","services":[{"broker_id":"12345678-9123-4567-8912-345678012pipeline","service_id":"private_worker","container":{"guid":"19c29990ffe42ce260f5a5cb64f54169","type":"resource_group_id"},"updated_at":"2020-01-29T15:13:03.872Z","parameters":{"label":"localAgentSidney2","name":"localAgentSidney2","workerQueueCredentials":"ZKhzotKWYOY3HRzlBdVtptYNiHbDg1LxxNbowH5FZiYN","workerQueueIdentifier":"ServiceId-669c1e5a-55de-4c89-8f89-04ac5952aae7"},"status":{"state":"configured"},"dashboard_url":"/devops/pipelines/worker/79fcc530-6084-4a13-9eb1-d46268821e01","region_id":"ibm:ys1:us-south","instance_id":"79fcc530-6084-4a13-9eb1-d46268821e01","description":"Run pipeline workloads on your own infrastructure.","tags":["ibm","deliver","build","deploy","pipeline","cicd"],"url":"https://otc-pipeline-broker.stage1.ng.bluemix.net/pipeline-broker/api","toolchain_binding":{"status":{"state":"configured"}}},{"broker_id":"fe8c9dae-f51c-4ff3-815f-f64c5a9b0a3e","service_id":"githubconsolidated","container":{"guid":"19c29990ffe42ce260f5a5cb64f54169","type":"resource_group_id"},"updated_at":"2020-01-28T14:46:39.627Z","parameters":{"extra_capabilities":[{"capability_id":"git.issues","display_name":"Issues","dashboard_url":"https://github.com/SidneyJiang/SimleTestWithMocha/issues","label":"SimleTestWithMocha","tags":["think","code"],"enabled":false,"readme":false}],"label":"SimleTestWithMocha","type":"link","legal":false,"git_id":"github","repo_url":"https://github.com/SidneyJiang/SimleTestWithMocha.git","private_repo":true,"has_issues":false,"auto_init":false,"enable_traceability":false,"authorized":"github","owner_id":"SidneyJiang","repo_name":"SimleTestWithMocha","api_root_url":"https://api.github.com","token_url":"https://otc-github-consolidated-broker.us-south.devops.dev.cloud.ibm.com/github/token?git_id=github"},"status":{"state":"configured"},"dashboard_url":"https://github.com/SidneyJiang/SimleTestWithMocha","region_id":"ibm:ys1:us-south","instance_id":"74895ba2-d6c9-4216-8a3e-eb883ae655d6","description":"Store and manage code on GitHub.com or on your own GitHub Enterprise server.","tags":["third-party","code","collaboration","scm","git","version-control","planning"],"url":"https://otc-github-consolidated-broker.stage1.ng.bluemix.net/github-broker/api","toolchain_binding":{"status":{"state":"configured"},"webhook_id":"10e85f7d6f9e80cf7f8683e5edb3a623"}},{"broker_id":"12345678-9123-4567-8912-345678012pipeline","service_id":"pipeline","container":{"guid":"19c29990ffe42ce260f5a5cb64f54169","type":"resource_group_id"},"updated_at":"2020-01-28T14:45:44.878Z","parameters":{"label":"TekPip","type":"tekton","name":"TekPip","ui_pipeline":true},"status":{"state":"configured"},"dashboard_url":"/devops/pipelines/tekton/94619026-912b-4d92-8f51-6c74f0692d90","region_id":"ibm:ys1:us-south","instance_id":"94619026-912b-4d92-8f51-6c74f0692d90","description":"Automate your builds, deployments, and more.","tags":["ibm","deliver","build","deploy","pipeline","cicd"],"url":"https://otc-pipeline-broker.stage1.ng.bluemix.net/pipeline-broker/api","toolchain_binding":{"status":{"state":"configured"},"webhook_id":"171f669bfd8db7e60ba10d645806ea29"}}]}
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        params:
        - name: another-pipeline-id
          value: $(params.another-pipeline-id)
        - name: manual-trigger
          value: $(params.manual-trigger)
        - name: repository
          value: $(params.repository)
        - name: toolchain-id
          value: $(params.toolchain-id)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: another-pipeline-id
      description: the pipeline Id of another tekton pipeline to trigger
      value: $(event.another-pipeline-id)
    - name: manual-trigger
      description: manual trigger name of another tekton pipeline
      value: $(event.manual-trigger)
    - name: apikey
      description: the ibmcloud api key
      value: $(event.apikey)
    - name: repository  # repository doesn't have to be in TriggerTemplate.params, but it has to be in resourcetemplates.PipelineRun.params
      value: $(event.repository)
    - name: toolchain-id
      value: $(event.toolchain-id)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template