apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
      - name: another-pipeline-id
        description: the pipeline Id of another tekton pipeline to trigger
      - name: another-pipeline-manual-trigger
        description: manual trigger name of another tekton pipeline
      - name: apikey
        description: the ibmcloud api key
      - name: devops-api
        description: the ibmcloud devops-api endpoint
      - name: api
        description: the ibmcloud api endpoint
  tasks:
    - name: pipeline-trigger-another-pipeline
      taskRef:
        name: trigger-another
      params:
        - name: another-pipeline-id
          value: $(params.another-pipeline-id)
        - name: another-pipeline-manual-trigger
          value: $(params.another-pipeline-manual-trigger)
        - name: apikey
          value: $(params.apikey)
        - name: devops-api
          value: $(params.devops-api)
        - name: api
          value: $(params.api)   