apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
      - name: another-pipeline-id
        description: the pipeline Id of another tekton pipeline to trigger
      - name: manual-trigger
        description: manual trigger name of another tekton pipeline
      - name: repository
        description: the git repository url that we interested in
      - name: toolchain-id
  tasks:
    - name: pipeline-trigger-another-pipeline
      taskRef:
        name: trigger-another
      params:
        - name: another-pipeline-id
          value: $(params.another-pipeline-id)
        - name: manual-trigger
          value: $(params.manual-trigger)
        - name: repository
          value: $(params.repository)
        - name: toolchain-id
          value: $(params.toolchain-id)