apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-text
spec:
  params:
    - name: deployBaseImage
      default: ibmcom/pipeline-base-image:latest
  stepTemplate:
    env:
      - name: TEXT
        valueFrom:
          configMapKeyRef:
            name: trigger-data
            key: TEXT
      - name: number
        valueFrom:
          configMapKeyRef:
            name: trigger-data
            key: number
      - name: merged
        valueFrom:
          configMapKeyRef:
            name: trigger-data
            key: merged
      - name: triggerparam
        valueFrom:
          configMapKeyRef:
            name: trigger-data
            key: triggerparam
  steps:
  - name: echo-text
    image: $(params.deployBaseImage)
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo "TEXT is '${TEXT}'"
          echo "number is '${number}'"
          echo "merged is '${merged}'"
          echo "triggerparam is '${triggerparam}'"