apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-text
spec:
  params:
    - name: deployBaseImage
      default: ibmcom/pipeline-base-image:latest
    - name: secretValue
  stepTemplate:
    env:
      - name: TEXT
        valueFrom:
          configMapKeyRef:
            name: trigger-data
            key: TEXT
      - name: API_KEY
        valueFrom:
          secretKeyRef:
            name: cd-secret
            key: API_KEY
  results:
    - name: pass-in-apikey-as-result
      description: APIKEY passed in
    - name: passdown
      description: something to pass down
  steps:
  - name: prepare
    image: bash:latest
    env:
      - name: SECRET_VALUE
        value: $(params.secretValue)
    script: |
        #!/usr/bin/env bash
        echo "TEXT is '${TEXT}'"
        TEXT=a_new_katen
        echo "TEXT is '${TEXT}'"
        echo -n "${TEXT}" > $(results.passdown.path)
        echo -n "${API_KEY}" > $(results.pass-in-apikey-as-result.path)
        echo -n "${SECRET_VALUE}"
  - name: echo-text-step
    image: $(params.deployBaseImage)
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo "TEXT is '${TEXT}'"
          echo "passdown is '${passdown}'"
          echo results.name.path is $(results.passdown.path)
          echo API_KEY is $(results.pass-in-apikey-as-result.path)