apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-text
spec:
  stepTemplate:
    env:
      - name: TEXT
        valueFrom:
          configMapKeyRef:
            name: trigger-data
            key: TEXT
      - name: repository
        valueFrom:
          configMapKeyRef:
            name: trigger-data
            key: repository
  steps:
  - name: echo-slack-text
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo "TEXT is '${TEXT}'"
          echo "repository is ${repository}"