apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-text
spec:
  params:
    - name: deployBaseImage
      default: ibmcom/pipeline-base-image:latest
    - name: eventpayload
  stepTemplate:
    env:
      - name: TEXT
        valueFrom:
          configMapKeyRef:
            name: trigger-data
            key: TEXT
  volumes:
    - name: trigger-data
      configMap:
        name: trigger-data
  results:
    - name: pass-in-apikey-as-result
      description: APIKEY passed in
    - name: passdown
      description: something to pass down
  steps:
  - name: prepare
    image: ibmcom/pipeline-base-image
    env:
      - name: EVENT_PAYLOAD
        value: $(params.eventpayload)
    script: |
        #!/usr/bin/env bash
        echo '${EVENT_PAYLOAD}'
        printf "\n"
        echo ${EVENT_PAYLOAD}
        printf "\n"
        echo ${EVENT_PAYLOAD} | jq
        printf "\n"
        echo '${TEXT}' | jq
        echo -n "${TEXT}" > $(results.passdown.path)
        echo -n "${API_KEY}" > $(results.pass-in-apikey-as-result.path)
    volumeMounts:
      - mountPath: /trigger-data
        name: trigger-data
  - name: echo-text-step
    image: $(params.deployBaseImage)
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo '${TEXT}' | jq
          printf "\n"
          cat /trigger-data/payload.json
          printf "\n"
          cat /trigger-data/payload.json | jq
          printf "\n"
          echo "passdown is '${passdown}'"
          echo results.name.path is $(results.passdown.path)
          echo API_KEY is $(results.pass-in-apikey-as-result.path)
    volumeMounts:
      - mountPath: /trigger-data
        name: trigger-data