apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-text
spec:
  params:
    - name: deployBaseImage
      default: ibmcom/pipeline-base-image:latest
  stepTemplate:
    env:
      - name: TEXT
        valueFrom:
          configMapKeyRef:
            name: trigger-data
            key: TEXT
  steps:
  - name: prepare
    image: $(params.deployBaseImage)
    command: ["/bin/sh", "-c"]
    args:
        - |
          export FROMSTEP1=a_good_token
  - name: echo-text
    image: $(params.deployBaseImage)
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo "TEXT is '${TEXT}'"
          echo "FROMSTEP1 is '${FROMSTEP1}'"