apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: task-pvc
      description: the output pvc - this is where the cloned repository will be stored
    - name: deployBaseImage
      default: node:14
    - name: apikey-from-echo-text
    - name: passdown-from-echo-text
  steps:
  - name: show-secrets
    image: alpine
    env:
      - name: apikey
        value: $(params.apikey-from-echo-text)
      - name: passdown
        value: $(params.passdown-from-echo-text)
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo apikey-from-echo-text is ${apikey}
          echo passdown-from-echo-text is ${passdown}
  - name: clone-a-repo
    image: $(params.deployBaseImage)
    imagePullPolicy: Always
    workingDir: /workspace
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo "Cloning repo"
          git config --global user.email "xinyij@us.ibm.com"
          git config --global user.name "Sidney Jiang"
          git config --global push.default matching
          git clone -q -b master https://github.com/SidneyJiang/simple-toolchain-20191105144723407
          ls
          sleep 1000s
          pwd
    volumeMounts:
      - mountPath: /workspace
        name: task-volume
  - name: build
    image: $(params.deployBaseImage)
    imagePullPolicy: Always
    workingDir: /workspace
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo "ls and pwd"
          ls
          pwd
          echo "cd .. and ls"
          cd ..
          ls
    volumeMounts:
      - mountPath: /workspace
        name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)