apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: git-clone
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc - this is where the cloned repository will be stored
      - name: deployBaseImage
        default: ibmcom/pipeline-base-image:latest
  steps:
  - name: clone-a-repo
    image: $(inputs.params.deployBaseImage)
    imagePullPolicy: Always
    workingDir: /workspace
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo "Cloning repo"
          git config --global user.email "xinyij@us.ibm.com"
          git config --global user.name "Sidney Jiang"
          git config --global push.default matching
          git clone -q -b master https://github.com/SidneyJiang/simple-toolchain-20191105144723407
          ls
          pwd
    volumeMounts:
      - mountPath: /workspace
        name: task-volume
  - name: build
    image: $(inputs.params.deployBaseImage)
    imagePullPolicy: Always
    workingDir: /workspace
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo "ls and pwd"
          ls
          pwd
          echo "cd .. and ls"
          cd ..
          ls
    volumeMounts:
      - mountPath: /workspace
        name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)