apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template-slack
spec:
  params:
    - name: triggerrepo
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: trigger-data
      data:
        SLACK_TOKEN: $(params.slacktoken)
        TRIGGER_REPO: $(params.triggerrepo)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-slack
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding-slack
spec:
  params:
    - name: slacktoken
      value: $(event.token)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: show-slack-token-listener
spec:
  triggers:
    - binding:
        name: binding-slack
      template:
        name: template-slack