apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template-slack
spec:
  params:
    - name: triggerrepo
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: trigger-data
      data:
        SLACK_TOKEN: $(params.slacktoken)
        TRIGGER_REPO: $(params.triggerrepo)
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: docker-build-sa
      imagePullSecrets:
        - name: private-registry-secret
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: test-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-slack
        serviceAccountName: docker-build-sa
        params:
          - name: pipeline-pvc
            value: test-$(uid)-pvc
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding-slack
spec:
  params:
    - name: slacktoken
      value: $(event.token)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: show-slack-token-listener
spec:
  triggers:
    - binding:
        name: binding-slack
      template:
        name: template-slack