apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template-slack
spec:
  params:
    - name: triggerrepo
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: trigger-data
      data:
        SLACK_TOKEN: $(params.slacktext)
        WEBHOOK_PAYLOAD: $(params.payload)
        TRIGGER_REPO: $(params.triggerrepo)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: test-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-slack
        params:
          - name: pipeline-pvc
            value: test-$(uid)-pvc
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding-slack
spec:
  params:
    - name: slacktext
      value: $(event.text)
    - name: payload
      value: $(event)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: show-slack-text-listener
spec:
  triggers:
    - binding:
        name: binding-slack
      template:
        name: template-slack