apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template-slack
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: trigger-data
      data:
        SLACK_TOKEN: $(params.slacktext)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: test-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-generic
        params:
          - name: pipeline-pvc
            value: test-$(uid)-pvc
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template-git
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: trigger-data
      data:
        repository: $(params.repository)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: test-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline-generic
        params:
          - name: pipeline-pvc
            value: test-$(uid)-pvc
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding-slack
spec:
  params:
    - name: slacktext
      value: $(event.text)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding-git
spec:
  params:
    - name: repository
      value: $(event.repository)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: show-slack-text-listener
spec:
  triggers:
    - binding:
        name: binding-slack
      template:
        name: template-slack
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: show-git-repository-listener
spec:
  triggers:
    - binding:
        name: binding-git
      template:
        name: template-git