# Task writes "some stuff" to a predefined path in the workspace git PipelineResource
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-token
spec:
  stepTemplate:
    env:
      - name: SLACK_TOKEN
        valueFrom:
          configMapKeyRef:
            name: slack-data
            key: SLACK_TOKEN
  steps:
  - name: echo-slack-token
    image: ubuntu
    command: ["/bin/sh", "-c"]
    args:
        - |
          echo "SLACK_TOKEN is ${SLACK_TOKEN}"
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline
spec:
  tasks:
    - name: console-log-token
      taskRef:
        name: echo-token
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: slack-data
      data:
        SLACK_TOKEN: $(params.slacktoken)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: slacktoken
      value: $(event.token)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: show-slack-token-listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
